### ISSUE TITLE
Can't run demo

### ISSUE THREAD

**Issue by JcmeLs** [react-native-community/cameraview#8]
Hi,When I run the demo project.I get this exception.Can you help to check?Thanks
```
2018-10-24 15:40:51.489 10902-10902/com.google.android.cameraview.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.cameraview.demo, PID: 10902
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.cameraview.demo/com.google.android.cameraview.demo.MainActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.google.android.cameraview.CameraView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.google.android.cameraview.CameraView
     Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.google.android.cameraview.CameraView
     Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]
        at java.lang.Class.getConstructor0(Class.java:2320)
        at java.lang.Class.getConstructor(Class.java:1725)
        at android.view.LayoutInflater.createView(LayoutInflater.java:619)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.google.android.cameraview.demo.MainActivity.onCreate(MainActivity.java:109)
        at android.app.Activity.performCreate(Activity.java:7050)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

**Comment by JcmeLs** [comment]
@sibelius Can you help to check?Very thanks.I saw the preview function you added on google's cameraview. I found that there is a black screen on Huawei p20 lite, but there is no such problem on Xiaomi mix2.  After use react-native-community's demo project, I found that the demo could not run. Can you help me with it?

**Comment by JcmeLs** [comment]
I add this code to fix crash issue.Can I do this?
``` 
    public CameraView(Context context, AttributeSet attrs) {
        this(context, attrs, false);
    }
```
